# Generated by Django 4.0 on 2022-01-08 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_user_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='rate',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
